import React from "react"

const Welcome=()=>
  <div className="Welcome">
    <h1>Welcome to the app</h1>
    <p styles={{fontSize:'50px'}}>
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean pretium accumsan lacus, sed vulputate dolor aliquam eget. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Pellentesque lacinia nibh ut justo commodo feugiat. Suspendisse sed nunc quis nibh porta aliquet. Nunc efficitur, diam sit amet congue commodo, velit diam commodo lectus, a malesuada nunc nunc ac tellus. Sed sagittis erat rhoncus lobortis lobortis. In hac habitasse platea dictumst. In sodales, nulla a congue blandit, sem risus gravida felis, laoreet eleifend nisl orci ut sem. Aenean id pulvinar nisl. Aenean feugiat iaculis sagittis. In molestie, leo et tristique auctor, enim massa vestibulum diam, a viverra enim orci at est. Sed mollis mattis eleifend. Integer imperdiet magna nisl, et blandit mauris vulputate a. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Pellentesque augue ex, malesuada et sem a, placerat sollicitudin erat. Nulla facilisi.

Curabitur in est quis enim pretium eleifend at blandit sapien. Praesent efficitur commodo vehicula. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Curabitur vitae blandit urna, quis facilisis augue. Aliquam bibendum justo nec massa eleifend, at vehicula sem lobortis. Etiam interdum non nulla sed vehicula. Nunc nec lectus erat. Donec venenatis justo nunc, id posuere purus suscipit id. Vivamus diam sem, consectetur a lorem eu, luctus malesuada est. Mauris malesuada sit amet urna ac viverra. Nulla vitae metus odio. In vitae est id arcu rhoncus sodales nec sed nulla. Quisque nec ultrices dui.

Nullam lacinia ultrices diam eu sodales. Aenean justo mi, molestie pretium est nec, mollis elementum justo. Integer sit amet leo nulla. Fusce ornare nunc ex, mollis viverra enim sagittis ut. Nullam non est tellus. Maecenas posuere justo sit amet quam sollicitudin, quis porta lacus rhoncus. Morbi faucibus, massa id ultrices mattis, justo lacus vulputate nulla, in auctor arcu ipsum id nulla. In condimentum lacinia dolor. Aenean porta nunc at dolor cursus efficitur. Nulla facilisi. Phasellus ullamcorper turpis sit amet vestibulum suscipit. Cras vel mauris risus. Fusce eu erat purus.

Nullam sit amet erat augue. Etiam eu metus metus. Etiam laoreet mauris eu lorem eleifend finibus. Aliquam ut massa non tellus porttitor fringilla non et sapien. Donec nec vulputate diam. Ut sagittis, odio at malesuada posuere, sem ante malesuada leo, eu porta elit sem sed massa. Vestibulum accumsan nunc sit amet dolor consectetur lacinia. Suspendisse eu leo mollis, dictum eros et, scelerisque augue. Etiam posuere ullamcorper lectus, non volutpat ipsum molestie a. Maecenas dignissim sem libero, euismod pellentesque justo venenatis non. Nulla convallis nisl eros, a tempus eros fringilla vel. Suspendisse potenti. Etiam pharetra diam consequat consequat congue. Nulla placerat pharetra dolor, at porttitor leo aliquet eu. Proin nec mauris lectus.

Nullam placerat risus est, sed venenatis purus pharetra eu. Suspendisse ultricies rhoncus arcu, non lacinia felis ornare ac. Cras tempus ultricies urna eu condimentum. Nam vestibulum tellus vel nisi vehicula facilisis. Nam id ultrices odio. Suspendisse potenti. Nulla euismod aliquam dolor vel rhoncus.

Aenean congue nisl lectus, eu luctus quam lobortis eget. Integer condimentum lectus vestibulum mi eleifend, quis sollicitudin nibh porta. Donec fringilla felis diam, sed hendrerit nisl placerat blandit. Morbi augue lorem, faucibus id magna ut, rhoncus dignissim urna. Quisque eu erat in nisl elementum posuere. Maecenas quis ante at ex accumsan auctor. Vivamus sit amet nunc non urna scelerisque pulvinar sed sed urna. Pellentesque elit nibh, auctor nec accumsan non, egestas eget lectus. Nullam a nibh vitae ligula porttitor vestibulum. Morbi velit magna, eleifend placerat semper sit amet, interdum quis enim. Donec interdum lacinia mi, eget consectetur velit rutrum quis. Pellentesque interdum tortor ut odio ullamcorper volutpat. Pellentesque dolor orci, blandit sit amet nisi ac, venenatis volutpat sem. Etiam hendrerit libero imperdiet semper scelerisque. Donec vehicula arcu id magna laoreet posuere.

Quisque porta magna a sem porttitor, ac iaculis lacus hendrerit. Curabitur efficitur consequat ex, vitae efficitur justo consectetur at. Donec venenatis orci nec erat convallis dignissim. Nam a malesuada dui. Praesent sit amet urna urna. Aliquam dictum eros odio. Aliquam ac erat eget ligula bibendum tristique. Praesent efficitur eu sem vitae posuere. Praesent non ante et leo volutpat consectetur vel vel felis. Nam elementum libero nec diam volutpat, sed dictum ipsum scelerisque. Etiam varius nisl eu leo pretium, vel interdum nibh placerat. Suspendisse rhoncus ex eros, vel vulputate libero pellentesque eu.

Vivamus ac varius ligula, non mollis nisi. Maecenas at eleifend erat, id dictum ex. Vestibulum vel tempor tellus. Nulla nec molestie erat, ut porttitor erat. Etiam pretium ultricies nunc quis accumsan. Pellentesque vulputate erat nec luctus eleifend. In eget mattis dolor, in convallis ex. Proin dictum erat a tempor molestie. Nunc ac tortor vitae massa suscipit elementum. In lobortis quam ligula, nec finibus diam ornare ut. Cras in sem at urna tincidunt dictum non vel tellus. Ut accumsan turpis at sapien luctus commodo. Quisque tristique lacus eu dolor aliquet, vitae elementum nulla feugiat. Nulla tincidunt fermentum lacus, sit amet ultricies ipsum tristique nec. Cras nec tempus dui.

Phasellus ipsum eros, ultricies ut mi non, blandit pharetra ex. Donec in placerat ipsum, quis facilisis mi. Aliquam convallis nec lorem id ullamcorper. Curabitur consequat dapibus fermentum. Pellentesque consectetur fringilla dolor ac vehicula. Sed vel tortor in urna condimentum pharetra vitae vestibulum nisi. Pellentesque fringilla ultrices sapien, et sodales orci imperdiet nec. Donec eget mi in libero tristique accumsan vel sed ante. Ut vulputate cursus suscipit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Cras placerat eros ac quam efficitur, id euismod sem malesuada.

Nulla molestie tempus pellentesque. Sed mattis enim vitae leo sagittis imperdiet. Vestibulum congue lobortis tellus vel mollis. Ut vitae sollicitudin purus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Cras suscipit blandit ornare. Phasellus vel justo vel diam ullamcorper sodales sit amet eget erat. Cras a mollis velit. In accumsan, risus maximus posuere imperdiet, ante neque eleifend orci, et ullamcorper odio lacus ut quam. Aliquam pulvinar mollis felis, ac consequat massa rhoncus sit amet. Quisque mollis bibendum posuere. Nam consectetur nec nibh id rhoncus. Etiam ultricies elit ac metus placerat eleifend.
    </p>
  </div>
export default Welcome